[reset_admin_password]
name = "Reset the admin password"
command = "/bin/bash scripts/actions/reset_admin_password"
accepted_return_codes = [0]
description = "Change the admin password of the app."
    [reset_admin_password.arguments]
        [reset_admin_password.arguments.password]
            type = "password"
            ask.en = "Set the password for the administration"
            ask.fr = "Définissez le mot de passe pour l'administration"